### ISSUE TITLE
Define terminology

### ISSUE THREAD

**Issue by oej** [CycloneDX/transparency-exchange-api#24]
We need to agree on terminology

* Avoid key terms used in SBOMs to avoid confusion
* Base on existing terminology
  * Proposal  https://niccs.cisa.gov/cybersecurity-career-resources/vocabulary  or this: https://csrc.nist.gov/glossary

Possibly create a doc in the repo for TEA-specific terms like

* TEA Index
* TEA Bundle
* TEA collection
* TEApot :-)

**Comment by taleodor** [comment]
Compiled a list of terms we are (or may be) using and those with some definitions in the referenced documents (not necessarily fitting definitions, just for faster search). 

Blank entries don't have definitions in these 2 glossary documents.

*Index*

*Bundle*

*Collection*
[https://csrc.nist.gov/glossary/term/collection](https://csrc.nist.gov/glossary/term/collection)
The first phase of the computer and network forensics process, which involves identifying, labeling, recording, and acquiring data from the possible sources of relevant data, while following guidelines and procedures that preserve the integrity of the data.

*Project*
[https://csrc.nist.gov/glossary/term/project](https://csrc.nist.gov/glossary/term/project)
Endeavor with defined start and finish criteria undertaken to create a product or service in accordance with specified resources and requirements.

*Product*
[https://csrc.nist.gov/glossary/term/project](https://csrc.nist.gov/glossary/term/product)
- Result of a process.
- Part of the equipment (hardware, software and materials) for which usability is to be specified or evaluated.
- A complete set of computer programs, procedures and associated documentation and data designed for delivery to a software consumer.
- A software application that has one or more capabilities.

*Branch*

*Feature Set*

*Release*
[https://csrc.nist.gov/glossary/term/release](https://csrc.nist.gov/glossary/term/release)
A collection of new and/or changed configuration items which are tested and introduced into a production environment together.

*Artifact*
[https://csrc.nist.gov/glossary/term/artifact](https://csrc.nist.gov/glossary/term/artifact)
- A piece of evidence
- Work products that are produced and used during a project to capture and convey information (e.g., models, source code).
- A piece of evidence, such as text or a reference to a resource, that is submitted to support a response to a question.
  
*Attachment*

**Comment by ppkarwasz** [comment]
I think we need to define first what the atomic unit (product?) in the index is.

For a hardware producer this might be a physical device, e.g. a WiFi router. These however usually have multiple detachable parts, e.g. a charger. If the charger is also sold separately, should the WiFi route be a bundle and not a product?

For a software company, I would say that a product is each element that can be downloaded separately, even if it is not sold separately. For example Apache Tomcat is a product with a binary distribution that you can download and run. However **each** one of the Apache Tomcat libraries is available separately and users often use some of these libraries to embed Tomcat in their project.

**Comment by oej** [comment]
I think the product is something the manufacturer hands over to the user. The same product can have many names and a "product" can be a bundle of many bundles of products.

In my view the API, the "product" is what is distributed, is the entry point in the index.  The creator of the TEI defines it. One entry point can have multiple TEIs pointing to it.

In the other end we have the TEI collection that is tied to a single product/unit with a version and artefacts for it. 

CycloneDX defines the thing that a BOM describes as "BOM metadata includes the supplier, manufacturer, and target component for which the BOM describes" - everything is a "component".

I don't think I make things clearer... It's early morning :-)

**Comment by taleodor** [comment]
Took a stab at combining Olle's original proposal with what I had in the API based on our research at Reliza and definitions above. Would appreciate feedback.

```
Component is a discrete identifiable information technology asset that represents a building block of a system and may include hardware, software, and firmware. Component has Branches that have Releases. A Release consists of one or more Deliverables. For example, for a software Release, a set of Deliverables may be: Debian package, MSI distribution, Container image. A Deliverable has Artifacts that can be a BOM or an Attachment, such as VEX, VDR, Attestation.

Bundle is a marketable representation of an identifiable information technology product. Bundle has Feature Sets that have Collections. A Collection consists of one or more Deliverables. A Collection is what the end-user buys. For example, for hardware, that would be a physical package that the client receives; for software, that would be a complete distribution that the client receives.

TEA Index represents a bundle - showing all Collections that are part of this Bundle.
```

I think for the TEA spec, the part related to Component may actually be omitted or made optional, but it's nice to keep this in mind in any case.

Below is the flow chart representation of the same thing I wrote in text:

![2024-08-03-tea-definition-diagram](https://github.com/user-attachments/assets/f8b4ee12-15bc-40ac-9180-d5eab97e2204)

**Comment by taleodor** [comment]
Alternative chart version that fits some additional use-cases:

_Here a Distribution is a physical package that the client receives. And a Collection is a set of Distributions that are marketable together. Version would be assigned at a Distribution level but Collection is assumed to have some shared Version prefix or same Marketing Version for all Distributions inside it._

I.e., a Collection could mean a database software distribution marketed with Version 1.0.1. Then it may have several platform specific Distributions: Windows, Linux32, Linux64, Mac. Distributions may also have additional dimensions represented as a flattened set, i.e. North American Windows Distribution; EMEA Linux64 Distribution, etc.

Updated diagram below (click to enlarge):

![2024-08-03-tea-definition-diagram_v2](https://github.com/user-attachments/assets/6a314e10-ef4d-45cf-abd0-03f4080382e9)

**Comment by oej** [comment]
I don't see any reason to separate BOMs from other files in phase one. Did you have any specific reason for doing so?

**Comment by oej** [comment]
Stuff that happens when you're on holiday. ha ha :-)

I still think we need one attachment object - could be that we have additional attributes for BOMs, like the BOM identifier.

**Comment by oej** [comment]
Checked https://github.com/CycloneDX/transparency-exchange-api/pull/22/files and I already had an optional BOM identifier in the definition of an artefact.

**Comment by goneall** [comment]
I'll need to see the use cases to understand how the above terminology applies and how we would translate those terms to SPDX terminology.

The definition of Component requiring some form of branch / release may (or may not) be overly constraining depending on how it is used.

In the SPDX discussions, we found it extremely useful to separate the concept of an [Artifact](https://spdx.github.io/spdx-spec/v3.0/model/Core/Classes/Artifact/) from the concept of a [Package](https://spdx.github.io/spdx-spec/v3.0/model/Software/Classes/Package/).  The latter is a form of Artifact which is "released or made available through distribution.  Packages require metadata like release versions, download locations and/or project home pages whereas Artifacts in general may not.  If TEA components are to be thought of like packages, having branch / release data may be fine.  If the components are to represent the more general Artifacts which may be embedded in a release but not released independently, it may be overly constraining.

**Comment by oej** [comment]
@goneall thank you for your feedback. There is a use case document in the repository if you are interested. I also have a pull request adding to it.

**Comment by oej** [comment]
This is the output from our last meeting and the brainstorm meeting

<img width="1227" alt="Screenshot 2024-08-15 at 11 54 31" src="https://github.com/user-attachments/assets/fd445970-8c57-42b3-9c98-907bda7e5296">
