### ISSUE TITLE
Brainstorm on TEA publisher client for CI/CD toolchains

### ISSUE THREAD

**Issue by oej** [CycloneDX/transparency-exchange-api#55]
I think we need a description of a TEA publisher tool that can be integrated into CI/CD toolchains.

**Comment by oej** [comment]
Meeting scheduled Wednesday Oct 16 at 16:00 CET. See slack channel.

**Comment by oej** [comment]
[tea-publish.key.pdf](https://github.com/user-attachments/files/17492255/tea-publish.key.pdf)

**Comment by oej** [comment]
We have docs in the PDF now.

**Comment by ppkarwasz** [comment]
Should we open issues to discuss how publishing to TEA would look for various ecosystems?

As I stated before, a TEA publisher REST API is probably not required in the first TEA versions.
For the Maven ecosystem I would expect TEA publishing to work as follows:

1. User publish artifacts with a `classifier` of `cyclonedx` or `sbom`, as they do now.
2. The Maven repository manager will expose those artifacts through some kind of additional TEA plugin. We probably should ask the main repository managers ([Sonatype Nexus](https://www.sonatype.com/products/sonatype-nexus-repository) and [JFrog](https://jfrog.com/)) how they feel about exporting the current repository metadata through TEA.

Do we have any contacts with JFrog?

**Comment by oej** [comment]
Moved discussion to #73
