### ISSUE TITLE
tea-requirements has incomplete statement?

### ISSUE THREAD

**Issue by madpah** [CycloneDX/transparency-exchange-api#63]
Ref: https://github.com/CycloneDX/transparency-exchange-api/blob/52e598226cd2e0f494cbdd27690f9a36b500d235/doc/tea-requirements.md?plain=1#L24

This section appears to be incomplete or missing something - I'm unclear what @oej .

**Comment by oej** [comment]
Good catch. I need to go back in time and see what was in my head. Or just rewrite.
