### ISSUE TITLE
Clarify format of `domain-name` in TEI

### ISSUE THREAD

**Issue by madpah** [CycloneDX/transparency-exchange-api#65]
See https://cyclonedx.slack.com/archives/C04LR6R9T8E/p1730984569287219

This is to track to resolution and decision whether `domain-name` portion of TEI is reverse of forwards format.

Example "forwards": `cyclonedx.org`

Example "reverse": `org.cyclonedx`

There are advantages of both, but it is currently not documented which is intended in the TEI.

FYI @stevespringett  @oej

**Comment by oej** [comment]
DNS names has a clear well documented format with TLD at the end. As this is a name intended for resolution in the DNS, and not as an DNS-independent identifier, I do not think doing the reverse would be helpful. It's not an IETF supported standard.

**Comment by oej** [comment]
And as a non-Java developer I did not think there was an alternative, so all examples are in FQDN form ;-)

You are right that it's not documented, it was assumed by me. We  obviously need to clarify.

**Comment by oej** [comment]
I think we're in agreement on using it the FQDN way as it is intended to be resolved using DNS. Let's close this.
