### ISSUE TITLE
SPEC: `/product` endpoints - incomplete

### ISSUE THREAD

**Issue by madpah** [CycloneDX/transparency-exchange-api#81]
`GET /product` returns a paginated list of `#/components/schemas/tea_product`, which includes fields such as `purl` and `barcode` currently.

However, there is no mechanism provided in the API Spec as it stands to set/provide fields for a Product beyond it's Name in `POST /product`

From: https://github.com/CycloneDX/transparency-exchange-api/pull/77#discussion_r1850139350

FYI @oej  @vpetersson

**Comment by vpetersson** [comment]
Maybe I'm missing something here, but you can do this.

* You initially create the product by issuing a `POST` to `/product`.
* Let's say you then forgot to add say a SKU to this, you would just issue a `PATCH` against `/product/<tea_product_identifier>` with the payload `{'sku': 'abc123'}`.

I do however now realize that this wasn't covered. Adding a PR shortly for this.

**Comment by madpah** [comment]
I'd provide the same contract for the initial `POST` and the subsequent `PATCH` @vpetersson.

**Comment by vpetersson** [comment]
d'oh! My bad yes, should of course be there too. Fixed that in the PR. Thanks for flagging.
