### ISSUE TITLE
DISCOVERY: Clarify the UUID TEI TYPE - align with standards

### ISSUE THREAD

**Issue by oej** [CycloneDX/transparency-exchange-api#90]
https://datatracker.ietf.org/doc/html/rfc9562 defines many versions of UUID.

We need to either specify ONE version we use in the TEI UUID type or allow for multiple types.

Multiple types could look like:

`tei:uuid:carloselectriccycles.com:uuidv3:234234-234-234-234-3`

Not sure if there would be any benefit from supporting multiple UUID types from the API/TEI point of view. Are we aware of any usage out there that we need to support?

**Comment by ppkarwasz** [comment]
I think that each producer can decide its own UUID type and even change UUID type in time. The only requirement I see is that the identifier must be **unique**, which means that `tei:carloselectriccyccles.com:turbo_bike` is a very poor choice of an identifier.

Note that UUIDs already contain the version number in their digits, so just using `uuid:<something>` identifiers should be fine. On the other hand the `uuid:` namespace should always be included in the identifier.
